abstract class AppStrings {
  static const String appName = 'Cash Flow',
      onBoardingTitle1 = 'Track your expenses with ease',
      onBoardingSubTitle1 =
          'Record your daily expenses and find out where your money is going',
      onBoardingTitle2 = 'Set up a customized budget',
      onBoardingSubTitle2 =
          'Create budgets for different categories and track your adherence to them',
      onBoardingTitle3 = 'Advanced financial analysis',
      onBoardingSubTitle3 =
          'Get detailed reports and charts to better understand your spending patterns',
      skip = 'Skip',
      next = 'Next',
      getStarted = 'Get Started',
      createAccount = 'Create Account',
      youHaveAccount = 'You have an account?',
      alreadyHaveAccount = 'Already have an account?',
      dontHaveAccount = 'Don’t have an account?',
      signUp = ' Sign Up',
      signIn = ' Sign In',
      email = 'Email',
      password = 'Password',
      confirmPassword = 'Confirm Password',
      forgotPassword = 'Forgot Password?',
      login = 'Login',
      welcome = 'Welcome!',
      back = 'Back',
      lets = "Let’s",
      start = "Start!",
      userName = "User Name",
      userNameError = "Please enter your user name",
      userNameErrorLength = "User name must be at least 3 characters",
      emailError = "Please enter your email",
      emailErrorFormat = "Email format is incorrect",
      emailErrorLength = "Email must be at least 3 characters",
      passwordError = "Please enter your password",
      passwordErrorMatch = "Password does not match",
      passwordErrorLength = "Password must be at least 5 characters",
      home = "Home",
      analytics = "Analytics",
      budgets = "Budgets",
      transactions = "Transactions",
      totalBalance = "Total Balance",
      totalBalanceFilter = "Total Balance Filter",
      cash = " Cash",
      bankAccount = "Bank Account",
      done = " Done",
      allAccounts = "All Accounts",
      account = " Account",
      income = "  Income",
      expenses = "Expenses",
      addTransaction = "Add Transaction",
      addTransactionTitle = "Add Transaction Title",
      addTransactionAmount = "Add Transaction Amount",
      addTransactionDate = "Add Transaction Date",
      category = "Category",
      amount = "Amount",
      date = "Date",
      description = "Description",
      title = "Title",
      selectDate = "Select Date",
      selectTime = "Select Time", requiredField = "This field is required";
}
